### ISSUE TITLE
I keep getting an error when trying to open a save from a Nintendo Switch

### ISSUE THREAD

**Issue by ahusking** [ooCONTAGIONoo/D3Editor#1]
I get the following error in the logs:

------ LOG DATA 7/25/2020 06:03:58 PM ------
[CRITICAL]
Method=MarshaledInvoke
Line=0
Message=   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at D3.Application.FrmMain.AddAccount(String selectedpath)
   at D3.Application.FrmMain.backgroundWorker_DoWork(Object sender, DoWorkEventArgs e)

Any advice?

**Comment by ooCONTAGIONoo** [comment]
Is the editor itself crashing, or is it just logging an error?

**Comment by ahusking** [comment]
So when i open the app, and try to open my account.dat i get the following error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at D3.Application.FrmMain.backgroundWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

Give me the option to continue (which just returns to the app, but doesn't open the file) or quit.

**Comment by Tonic-Box** [comment]
Just popping by to help. So, for switch to load you need your account.dat to be completely fresh. Your toon files will load just fine but the account.dat needs to be fresh and unplayed.
